[
  ./terror.png
  ./snow_time.png
  ./jagged_peaks.png
  ./winter_canvas.png
  ./phoenix_sunset.png
  ./the_purple_hour.png
  ./between_the_buildings.png
  ./between_light_and_dark.png
  ./california_desert_wildflower_bloom.png
]
